### ISSUE TITLE
New ruby version is not always set on a ruby update deploy

### ISSUE THREAD

**Issue by JohannaHartmann** [makandra/capistrano-opscomplete#19]
Steps to reproduce:

- Change a project's ruby version
- Deploy this project and abort after new ruby version has been installed
- Try to deploy again

The second deploy may fail since capistrano-opscomplete does not use the new ruby version in this case. This may be the case if the Gemfile contains gems with native extensions (e.g. nokogiri or pg).

Normally capistrano-opscomplete takes care of setting the correct ruby version after changing it.
See https://github.com/makandra/capistrano-opscomplete/blob/master/lib/capistrano/opscomplete/ruby.rake#L109

**Comment by crigertg** [comment]
From the procedure how setting and installing ruby versions works I'm not sure how the problem can happen. 
I tried to reproduce it but I'm not able to. 
First deploy with change ruby version and cancel after installation:

```
...
00:05 opscomplete:ruby:update_ruby_build
      01 git pull -q
    ✔ 01 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.502s
      app01-stage.makandra.makandra.de: Configured Ruby version is not installed, but available for installation.
      02 rbenv install '2.6.2'
      02 Installing ruby-2.6.2...
      02 Installed ruby-2.6.2 to /home/deploy-capistrano-opscomplete_s/.rbenv/versions/2.6.2
      02
^C(Backtrace restricted to imported tasks)
cap aborted!
Interrupt: 

Tasks: TOP => opscomplete:ruby:ensure
(See full trace by running task with --trace)
The deploy has failed with an error: 


** DEPLOY FAILED
```

The following deploy:

```
...
00:05 opscomplete:ruby:update_ruby_build
      01 git pull -q
    ✔ 01 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.483s
      app01-stage.makandra.makandra.de: Ruby 2.6.2 is installed.
      02 rbenv global '2.6.2'
    ✔ 02 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.095s
00:08 opscomplete:ruby:install_bundler
      01 rbenv exec gem install bundler --no-document --version '2.0.2' --force
      01 Successfully installed bundler-2.0.2
      01 1 gem installed
    ✔ 01 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.771s
00:09 opscomplete:ruby:rehash
      01 rbenv rehash
    ✔ 01 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.126s
00:09 bundler:config
      01 bundle config --local deployment true
      01 You are replacing the current local value of deployment, which is currently nil
    ✔ 01 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.297s
      02 bundle config --local path /var/www/capistrano-opscomplete_s/shared/bundle
      02 You are replacing the current local value of path, which is currently nil
    ✔ 02 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.300s
      03 bundle config --local without development:test
      03 You are replacing the current local value of without, which is currently nil
    ✔ 03 deploy-capistrano-opscomplete_s@app01-stage.makandra.makandra.de 0.294s
00:11 bundler:install
...
```

If this is still a problem we need further information to debug this. 

Because this happened months ago I suppose that we can't get any more detailed error output.

**Comment by makmic** [comment]
Thanks for looking into this!
As the issue is already quite old I cannot recall too many details, but [this card is very related](https://makandracards.com/makandra/477884-bundler-in-deploy-mode-shares-gems-between-patch-level-ruby-versions). I think these preconditions are required to reproduce the issue:
* The new Ruby version should be a minor version change (e.g. 2.6.6.)
* The old Ruby version was already deployed (e.g. 2.6.5.)
* The Gemfile includes a gem with native extensions (e.g. `gem 'nokogiri'`)

**Comment by crigertg** [comment]
So the issue is probably this one?

> A deploy task fails because of incompatible gem dependencies

> This is most likely if your first deploy failed (but bundled the new versions), and the second deploy requires some of those gems. A common example is our "warn if there are any migrations" task. You will see an error like this:

  ```
      01 bundle exec rake db:warn_if_pending_migrations
      01 rake aborted!
      01 LoadError: incompatible library version - ./shared/bundle/ruby/2.5.0/gems/pg-0.18.4/lib/pg_ext.so
      01 ./shared/bundle/ruby/2.5.0/gems/pg-0.18.4/lib/pg.rb:4:in `require'
  ```

**Comment by makmic** [comment]
Yes, most likely it was this one.

**Comment by crigertg** [comment]
I think it's important to record that this is not a `capistrano-opscomplete` problem as this particular situation can also happen with manual ruby management. Furthermore if the problem occurs it's not just a problem with subsequent deployments but with the application running on the application servers. When the application using the old ruby version restarts it will probably fail. The real issue is with bundling gems not for different minor versions (but we can't change that). 

I thought about some possible solutions:

1. The `opscomplete:ruby:ensure` task could run before (for e.g. `db:warn_if_pending_migrations`) it would change the ruby version and try to bundle again before any remote tasks which depend on bundled gems can fail. Would this be a possible attempt? Eventually it's a problem for these kind of taks on initial deployments too, right? So tasks depending on gems which need to be bundled should be executed after bundling. 

2. If we want to work around these kind of issues in `capistrano-opscomplete` we would need to implement rollback tasks, which could introduce new issues. For e.g. we would need to determine which ruby version was used before on the server and do ` bundle exec gem pristine --all` (which should fix the issue) when rolling back. If we add this task it should only run if it's really necessary because it may run for long time (depending on the gems used for the project) and I'm not sure if we're able to implement it that way.  :thinking:

**Comment by makmic** [comment]
I think it is generally a good idea to perform the Ruby-installing task as soon as possible. Usually, it already happens soon after the new release directory was created:
```
after 'deploy:updating', 'opscomplete:ruby:ensure'
```

Solution 1) does however not solve the underlying problem that the server's Ruby version is corrupted if _any_ later deploy task fails. Personally I think we should rather go with 2). It might be quite complicated to implement properly, but seems to be the proper way to handle the issue "once and for all".

If we restrict the version downgrade to rollbacks where the Ruby version actually has changed I don't think performance would be an issue. I'm not sure however if `gem pristine -all` has any side effects on running ruby processes or not, but I wouldn't think so.
